public with sharing class Calculator {
  public static integer doAdd(integer number1, integer number2) {
    return number1 + number2;
  }
  public static integer doSub(integer number1, integer number2) {
    return number1 - number2;
  }
  public static integer doMul(integer number1, integer number2) {
    return number1 * number2;
  }
  public static integer doDiv(integer number1, integer number2) {
    return number1 / number2;
  }
}
